package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.prosecution.documentqueue.command.api.accesscontrol.RuleConstants;
import java.util.Arrays;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Update Document Status"
  when
    $outcome: Outcome();
    $action: Action(name == "documentqueue.update-document-status");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getReviewDocumentsAccessGroups()));
  then
    $outcome.setSuccess(true);
end

rule "Attach Document"
  when
    $outcome: Outcome();
    $action: Action(name == "documentqueue.attach-document");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getReviewDocumentsAccessGroups()));
  then
    $outcome.setSuccess(true);
end