#%RAML 0.8
title: Document Queue Query view
baseUri: http://localhost:8080/documentqueue-query-view/query/view/rest/documentqueue

/documents:
  get:
    description: |
      Get documents
      ...
      (mapping):
          responseType: application/vnd.documentqueue.query.documents+json
          name: documentqueue.query.documents
      ...
    queryParameters:
      status:
        description: Document Status
        type: string
        required: false
      source:
        description: Source of Document
        type: string
        required: false

    responses:
        200:
          description: OK
          body:
                application/vnd.documentqueue.query.documents+json:
                    example:  !include json/documentqueue.query.documents.json
                    schema:  !include json/schema/documentqueue.query.documents.json

/documents/counts:
   get:
      description: |
        Get document counts
        ...
        (mapping):
            responseType: application/vnd.documentqueue.query.documents-counts+json
            name: documentqueue.query.documents-counts
        ...
      responses:
          200:
            description: OK
            body:
                  application/vnd.documentqueue.query.documents-counts+json:
                      example: !include json/documentqueue.query.documents-counts.json
                      schema:  !include json/schema/documentqueue.query.documents-counts.json

/documents/{documentId}/content:
  description: gets document content information from document on the queue
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.documentqueue.query.document-content+json
          name: documentqueue.query.document-content
      ...
    responses:
      200:
        body:
          application/vnd.documentqueue.query.document-content+json:
            example:  !include json/documentqueue.query.document-content-view.json
            schema:  !include json/schema/documentqueue.query.document-content-view.json

/documents/{documentId}:
  description: gets document on the queue
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.documentqueue.query.get-document+json
          name: documentqueue.query.get-document
      ...
    responses:
      200:
        body:
          application/vnd.documentqueue.query.get-document+json:
            example:  !include json/documentqueue.query.get-document.json
            schema:  !include json/schema/documentqueue.query.get-document.json
